from __future__ import annotations

from maref.tools.browser_server import DomainWhitelist, create_browser_server
from maref.tools.email_server import (
    MockEmailBackend,
    RecipientWhitelist,
    SensitiveWordFilter,
    create_email_server,
)
from maref.tools.file_server import PathSandbox, PathSandboxError, create_file_server
from maref.tools.git_server import GitServer, RepoWhitelist, create_git_server
from maref.tools.registry import ToolRegistry
from maref.tools.shell_server import CommandWhitelist, create_shell_server
from maref.tools.tool_schema import (
    ToolCategory,
    ToolDefinition,
    ToolParameter,
    ToolRiskLevel,
    create_browser_tool,
    create_email_tool,
    create_file_tool,
    create_git_tool,
    create_shell_tool,
    create_web_search_tool,
    get_tool_definition,
    list_tool_definitions,
)
from maref.tools.unified_registry import (
    ROLE_CAPABILITY_ALLOWLIST,
    ROLE_RISK_CEILING,
    AgentRole,
    CapabilityType,
    ExecutionMode,
    FunctionCapabilityAdapter,
    HarnessCapabilityAdapter,
    HitlGate,
    MCPCapabilityAdapter,
    PermissionMiddleware,
    PermissionRequest,
    PermissionVerdict,
    RegisteredCapability,
    RiskLevelCeiling,
    RoleCapabilityFilter,
    ToolCallContext,
    ToolCallRecord,
    TrustLevelOverride,
    UnifiedToolRegistry,
)
from maref.tools.web_search_server import (
    DomainBlacklist,
    QuerySanitizer,
    ResultLimit,
    create_web_search_server,
)

__all__ = [
    # Existing exports
    "PathSandbox",
    "PathSandboxError",
    "create_file_server",
    "CommandWhitelist",
    "create_shell_server",
    "RepoWhitelist",
    "GitServer",
    "create_git_server",
    "DomainWhitelist",
    "create_browser_server",
    "RecipientWhitelist",
    "SensitiveWordFilter",
    "MockEmailBackend",
    "create_email_server",
    "QuerySanitizer",
    "ResultLimit",
    "DomainBlacklist",
    "create_web_search_server",
    "ToolRegistry",
    "ToolDefinition",
    "ToolRiskLevel",
    "ToolCategory",
    "ToolParameter",
    "create_file_tool",
    "create_shell_tool",
    "create_git_tool",
    "create_browser_tool",
    "create_email_tool",
    "create_web_search_tool",
    "get_tool_definition",
    "list_tool_definitions",
    # Unified registry exports
    "CapabilityType",
    "ExecutionMode",
    "ToolCallContext",
    "ToolCallRecord",
    "PermissionVerdict",
    "PermissionRequest",
    "PermissionMiddleware",
    "AgentRole",
    "ROLE_CAPABILITY_ALLOWLIST",
    "ROLE_RISK_CEILING",
    "RoleCapabilityFilter",
    "RiskLevelCeiling",
    "HitlGate",
    "TrustLevelOverride",
    "MCPCapabilityAdapter",
    "HarnessCapabilityAdapter",
    "FunctionCapabilityAdapter",
    "RegisteredCapability",
    "UnifiedToolRegistry",
]
