from __future__ import annotations

import ast
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from unittest.mock import MagicMock, patch

from maref.recursive.self_executor import (
    ASTSandbox,
    ASTValidationResult,
    AtomicDeployer,
    CodeGenerator,
    ExecutionPipelineRecord,
    ExecutionResult,
    ExecutionStage,
    GeneratedCode,
    SelfExecutor,
)
from maref.recursive.unified_audit import UnifiedAuditStore


@dataclass
class MockProposal:
    proposal_id: str
    change_type: object = None
    rationale: str = ""
    current_arch: str = ""
    proposed_arch: str = ""
    target_files: list[str] | None = None
    affected_symbols: list[str] | None = None


class TestExecutionStage:
    @pytest.mark.slow
    def test_values(self) -> None:
        assert ExecutionStage.CODE_GEN.value == "code_generation"
        assert ExecutionStage.AST_VALIDATE.value == "ast_validation"
        assert ExecutionStage.SAFETY_GATE.value == "safety_gate"
        assert ExecutionStage.DEPLOY.value == "deployment"
        assert ExecutionStage.VERIFY.value == "verification"
        assert ExecutionStage.ROLLBACK.value == "rollback"
        assert ExecutionStage.COMPLETE.value == "complete"


class TestGeneratedCode:
    @pytest.mark.slow
    def test_default_construction(self) -> None:
        g = GeneratedCode(file_path="/tmp/f.py", content="x=1", target_module="mod")
        assert g.file_path == "/tmp/f.py"
        assert g.content == "x=1"
        assert g.target_module == "mod"
        assert g.language == "python"


class TestASTValidationResult:
    @pytest.mark.slow
    def test_default_construction(self) -> None:
        r = ASTValidationResult(is_valid=True)
        assert r.is_valid is True
        assert r.errors == []
        assert r.warnings == []
        assert r.ast_tree is None
        assert r.imports == []
        assert r.classes_found == []
        assert r.functions_found == []


class TestExecutionResult:
    @pytest.mark.slow
    def test_construction(self) -> None:
        r = ExecutionResult(stage=ExecutionStage.DEPLOY, success=True, message="ok")
        assert r.stage == ExecutionStage.DEPLOY
        assert r.success is True
        assert r.is_failure is False
        assert r.timestamp > 0

    @pytest.mark.slow
    def test_is_failure(self) -> None:
        r = ExecutionResult(stage=ExecutionStage.DEPLOY, success=False, message="fail")
        assert r.is_failure is True


class TestExecutionPipelineRecord:
    @pytest.mark.slow
    def test_default_construction(self) -> None:
        r = ExecutionPipelineRecord(pipeline_id="p1", proposal_id="prop1")
        assert r.pipeline_id == "p1"
        assert r.proposal_id == "prop1"
        assert r.stages == []
        assert r.final_state == "unknown"
        assert r.rollback_performed is False
        assert r.start_time > 0
        assert r.end_time == 0.0

    @pytest.mark.slow
    def test_finish_sets_end_time(self) -> None:
        r = ExecutionPipelineRecord(pipeline_id="p1", proposal_id="prop1")
        r.finish()
        assert r.end_time > 0

    @pytest.mark.slow
    def test_duration_ms(self) -> None:
        r = ExecutionPipelineRecord(pipeline_id="p1", proposal_id="prop1")
        r.start_time = 1000.0
        r.end_time = 1002.0
        assert r.duration_ms == 2000.0

    @pytest.mark.slow
    def test_duration_ms_no_end_time(self) -> None:
        r = ExecutionPipelineRecord(pipeline_id="p1", proposal_id="prop1")
        r.start_time = 1000.0
        assert r.duration_ms > 0

    @pytest.mark.slow
    def test_to_audit_records(self) -> None:
        r = ExecutionPipelineRecord(pipeline_id="p1", proposal_id="prop1")
        r.stages.append(
            ExecutionResult(
                stage=ExecutionStage.CODE_GEN, success=True, message="gen ok"
            )
        )
        records = r.to_audit_records(round_num=31)
        assert len(records) == 1
        assert records[0].outcome == "success"
        assert records[0].event_type == "self_executor_code_generation"

    @pytest.mark.slow
    def test_to_audit_records_failure(self) -> None:
        r = ExecutionPipelineRecord(pipeline_id="p1", proposal_id="prop1")
        r.stages.append(
            ExecutionResult(
                stage=ExecutionStage.DEPLOY, success=False, message="fail"
            )
        )
        records = r.to_audit_records(round_num=31)
        assert records[0].outcome == "failure"


class TestCodeGenerator:
    @pytest.mark.slow
    def test_generate_generic(self) -> None:
        cg = CodeGenerator()
        proposal = MockProposal(proposal_id="pid1", rationale="do something")
        generated = cg.generate(proposal, project_root="/tmp")
        assert len(generated) == 1
        assert "Auto-generated by SelfExecutor" in generated[0].content
        assert generated[0].target_module is not None

    @pytest.mark.slow
    def test_generate_refactor(self) -> None:
        cg = CodeGenerator()
        proposal = MockProposal(
            proposal_id="p1",
            rationale="refactor module for clarity",
            proposed_arch="new_arch",
        )
        generated = cg.generate(proposal, project_root="/tmp")
        assert len(generated) >= 1
        assert "R31AutoGenerated" in generated[0].content

    @pytest.mark.slow
    def test_generate_add_tests(self) -> None:
        cg = CodeGenerator()

        class ChangeType:
            value = "add_test"

        proposal = MockProposal(
            proposal_id="p2",
            rationale="need test coverage",
            change_type=ChangeType(),
        )
        generated = cg.generate(proposal, project_root="/tmp")
        assert len(generated) >= 1
        assert "class Test" in generated[0].content

    @pytest.mark.slow
    def test_generated_tests_do_not_use_assert_true_placeholder(self) -> None:
        cg = CodeGenerator()

        class ChangeType:
            value = "add_test"

        with tempfile.TemporaryDirectory() as tmp:
            proposal = MockProposal(
                proposal_id="p-test",
                rationale="need test coverage",
                change_type=ChangeType(),
                target_files=[os.path.join(tmp, "tests", "test_generated.py")],
            )
            generated = cg.generate(proposal, project_root=tmp)
            assert "assert True" not in generated[0].content

    @pytest.mark.slow
    def test_generate_remove_unused_imports(self) -> None:
        cg = CodeGenerator()

        class ChangeType:
            value = "remove_unused_import"

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False
        ) as f:
            f.write("import os\nimport sys\nx = 1\n")
            tmp_path = f.name

        try:
            proposal = MockProposal(
                proposal_id="p3",
                rationale="unused import cleanup",
                change_type=ChangeType(),
                target_files=[tmp_path],
                affected_symbols=["os"],
            )
            generated = cg.generate(proposal, project_root="/tmp")
            assert len(generated) == 1
            assert "os" not in generated[0].content
            assert "sys" in generated[0].content
        finally:
            os.unlink(tmp_path)

    @pytest.mark.slow
    def test_classify_proposal_by_rationale(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="p", rationale="add tests for coverage")
        assert cg._classify_proposal(p) == "add_tests"

    @pytest.mark.slow
    def test_classify_proposal_cleanup_rationale(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="p", rationale="cleanup unused imports")
        assert cg._classify_proposal(p) == "remove_unused_imports"

    @pytest.mark.slow
    def test_classify_proposal_refactor_rationale(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="p", rationale="restructure module")
        assert cg._classify_proposal(p) == "refactor_module"

    @pytest.mark.slow
    def test_resolve_target_path_with_current_arch(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="p1", current_arch="some/path.py")
        path = cg._resolve_target_path(p, project_root="/tmp")
        assert "r31_executor_generated" in str(path)

    @pytest.mark.slow
    def test_generate_remove_imports_bad_file_returns_none(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="p", target_files=["/nonexistent/file.py"])
        result = cg._generate_remove_imports(p, Path("/nonexistent/file.py"))
        assert result is None


class TestASTSandbox:
    @pytest.mark.slow
    def test_validate_valid_code(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/f.py",
            content="import os\nx = 1\n",
            target_module="mod",
        )
        result = sandbox.validate(code)
        assert result.is_valid is True
        assert result.imports == ["os"]

    @pytest.mark.slow
    def test_validate_syntax_error(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/f.py",
            content="def foo(:\n",
            target_module="mod",
        )
        result = sandbox.validate(code)
        assert result.is_valid is False
        assert any("SyntaxError" in e for e in result.errors)

    @pytest.mark.slow
    def test_check_imports_blocked(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/f.py",
            content="import some_random_unknown_lib_xyz\n",
            target_module="mod",
        )
        result = sandbox.validate(code)
        assert any("Unknown import" in w for w in result.warnings)

    @pytest.mark.slow
    def test_check_dangerous_calls_eval(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/f.py",
            content="eval('x + 1')\n",
            target_module="mod",
        )
        result = sandbox.validate(code)
        assert result.is_valid is False
        assert any("Dangerous" in e for e in result.errors)

    @pytest.mark.slow
    def test_check_dangerous_calls_exec(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/f.py",
            content="exec('x = 1')\n",
            target_module="mod",
        )
        result = sandbox.validate(code)
        assert result.is_valid is False
        assert any("exec" in e for e in result.errors)

    @pytest.mark.slow
    def test_check_dangerous_getattr_bypass(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/f.py",
            content="getattr(obj, 'exec')\n",
            target_module="mod",
        )
        result = sandbox.validate(code)
        assert result.is_valid is False

    @pytest.mark.slow
    def test_extract_definitions(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/f.py",
            content="class Foo: pass\ndef bar(): pass\n",
            target_module="mod",
        )
        result = sandbox.validate(code)
        assert "Foo" in result.classes_found
        assert "bar" in result.functions_found

    @pytest.mark.slow
    def test_allowed_modules_set(self) -> None:
        assert "maref" in ASTSandbox.ALLOWED_MODULES
        assert "pytest" in ASTSandbox.ALLOWED_MODULES

    @pytest.mark.slow
    def test_blocked_imports_set(self) -> None:
        assert "eval" in ASTSandbox.BLOCKED_IMPORTS
        assert "exec" in ASTSandbox.BLOCKED_IMPORTS

    @pytest.mark.slow
    def test_resolve_attribute(self) -> None:
        code = "a.b.c()"
        tree = ast.parse(code)
        call = tree.body[0].value
        result = ASTSandbox._resolve_attribute(call.func)
        assert result == "a.b.c"


class TestAtomicDeployer:
    @pytest.mark.slow
    def test_construction_creates_backup_dir(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            backup = os.path.join(tmp, "backups")
            d = AtomicDeployer(backup_dir=backup)
            assert os.path.exists(backup)
            assert d._deployed == {}

    @pytest.mark.slow
    def test_deploy_creates_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            d = AtomicDeployer(backup_dir=os.path.join(tmp, "backups"))
            file_path = os.path.join(tmp, "out.py")
            code = GeneratedCode(
                file_path=file_path, content="x = 1", target_module="mod"
            )
            result = d.deploy(code)
            assert result.success is True
            assert os.path.exists(file_path)
            assert file_path in d._deployed

    @pytest.mark.slow
    def test_deploy_overwrites_and_backs_up(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            file_path = os.path.join(tmp, "out.py")
            Path(file_path).write_text("original")
            d = AtomicDeployer(backup_dir=os.path.join(tmp, "backups"))
            code = GeneratedCode(
                file_path=file_path, content="updated", target_module="mod"
            )
            result = d.deploy(code)
            assert result.success is True
            assert Path(file_path).read_text() == "updated"

    @pytest.mark.slow
    def test_deploy_failure(self) -> None:
        # Mock os.makedirs before creating AtomicDeployer
        with patch("os.makedirs") as mock_makedirs:
            # First call in __init__ should succeed
            # Second call in deploy should fail
            mock_makedirs.side_effect = [None, OSError("Permission denied")]
            d = AtomicDeployer(backup_dir="/tmp/backups")
            code = GeneratedCode(
                file_path="/tmp/out.py",
                content="x=1",
                target_module="mod",
            )
            result = d.deploy(code)
            assert result.success is False

    @pytest.mark.slow
    def test_rollback_no_backup(self) -> None:
        d = AtomicDeployer(backup_dir="/tmp/backups")
        result = d.rollback("/nonexistent/file.py")
        assert result.success is False
        assert "No backup found" in result.message

    @pytest.mark.slow
    def test_rollback_success(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            file_path = os.path.join(tmp, "out.py")
            Path(file_path).write_text("original")
            d = AtomicDeployer(backup_dir=os.path.join(tmp, "backups"))
            code = GeneratedCode(
                file_path=file_path, content="updated", target_module="mod"
            )
            d.deploy(code)
            assert Path(file_path).read_text() == "updated"
            rollback_result = d.rollback(file_path)
            assert rollback_result.success is True
            assert Path(file_path).read_text() == "original"

    @pytest.mark.slow
    def test_verify_deployed_match(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            file_path = os.path.join(tmp, "out.py")
            Path(file_path).write_text("content")
            d = AtomicDeployer(backup_dir=os.path.join(tmp, "backups"))
            result = d.verify_deployed(file_path, "content")
            assert result.success is True

    @pytest.mark.slow
    def test_verify_deployed_mismatch(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            file_path = os.path.join(tmp, "out.py")
            Path(file_path).write_text("actual")
            d = AtomicDeployer(backup_dir=os.path.join(tmp, "backups"))
            result = d.verify_deployed(file_path, "expected")
            assert result.success is False

    @pytest.mark.slow
    def test_verify_deployed_file_not_found(self) -> None:
        d = AtomicDeployer(backup_dir="/tmp/backups")
        result = d.verify_deployed("/nonexistent.py", "x")
        assert result.success is False

    @pytest.mark.slow
    def test_deployed_files_property(self) -> None:
        d = AtomicDeployer(backup_dir="/tmp/backups")
        assert d.deployed_files == []


class TestSelfExecutor:
    @pytest.mark.slow
    def test_default_construction(self) -> None:
        e = SelfExecutor()
        assert e.max_rounds == 3
        assert e.history == []
        assert e.deployed_files == []

    @pytest.mark.slow
    def test_custom_construction(self) -> None:
        store = UnifiedAuditStore()
        e = SelfExecutor(max_rounds=5, project_root="/tmp", audit_store=store)
        assert e.max_rounds == 5
        assert e._project_root == "/tmp"

    @pytest.mark.slow
    def test_execute_code_gen_failure(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")

        with patch.object(e._code_gen, "generate", return_value=[]):
            result = e.execute(proposal)
            assert result.final_state == "FAILED_CODE_GEN"

    @pytest.mark.slow
    def test_execute_ast_validation_failure(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")

        code = GeneratedCode(
            file_path="/tmp/f.py", content="invalid syntax {{", target_module="mod"
        )
        with patch.object(e._code_gen, "generate", return_value=[code]):
            result = e.execute(proposal)
            assert result.final_state == "FAILED_AST_VALIDATE"

    @pytest.mark.slow
    def test_execute_constitution_harness_blocked(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / "src" / "maref" / "recursive" / "meta_agent_closure.py"
            target.parent.mkdir(parents=True)
            target.write_text("ORIGINAL = True\n")
            e = SelfExecutor(project_root=tmp)
            proposal = MockProposal(
                proposal_id="p-constitution",
                change_type="refactor_module",
                target_files=[str(target)],
                proposed_arch="meta_agent_closure",
                rationale="modify red lines",
            )

            result = e.execute(proposal)

            assert result.final_state == "FAILED_SAFETY_GATE"
            assert target.read_text() == "ORIGINAL = True\n"

    @pytest.mark.slow
    def test_execute_safety_gate_blocked(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")

        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )

        mock_threat = MagicMock()
        mock_threat.blocked = True
        mock_threat.threat_type = "core_removal"
        mock_threat.reason = "simulated block"

        with (
            patch.object(e._code_gen, "generate", return_value=[code]),
            patch.object(
                e._safety_gate,
                "detect_core_removal",
                return_value=mock_threat,
            ),
        ):
            result = e.execute(proposal)
            assert result.final_state == "FAILED_SAFETY_GATE"

    @pytest.mark.slow
    def test_execute_deploy_failure_rollback(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")

        code = GeneratedCode(
            file_path="/nonexistent_dir_xyz/f.py",
            content="x = 1",
            target_module="mod",
        )

        mock_no_threat = MagicMock()
        mock_no_threat.blocked = False
        mock_no_threat.threat_type = ""
        mock_no_threat.reason = ""

        with (
            patch.object(e._code_gen, "generate", return_value=[code]),
            patch.object(
                e._safety_gate,
                "detect_core_removal",
                return_value=mock_no_threat,
            ),
            patch.object(e._safety_gate, "detect_combinatorial_explosion", return_value=mock_no_threat),
            patch.object(e, "_do_ai_stench_check", return_value=None),
            patch.object(e, "_do_intent_drift_check", return_value=None),
        ):
            result = e.execute(proposal)
            assert "ROLLED_BACK" in result.final_state

    @pytest.mark.slow
    def test_execute_verify_failure_rollback(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            e = SelfExecutor(project_root=tmp)
            proposal = MockProposal(proposal_id="p1")

            file_path = os.path.join(tmp, "test_out.py")
            code = GeneratedCode(
                file_path=file_path, content="x = 1", target_module="mod"
            )

            mock_no_threat = MagicMock()
            mock_no_threat.blocked = False

            with (
                patch.object(e._code_gen, "generate", return_value=[code]),
                patch.object(
                    e._safety_gate,
                    "detect_core_removal",
                    return_value=mock_no_threat,
                ),
                patch.object(e._safety_gate, "detect_combinatorial_explosion", return_value=mock_no_threat),
                patch.object(e, "_do_ai_stench_check", return_value=None),
                patch.object(e, "_do_intent_drift_check", return_value=None),
                patch.object(
                    e._deployer,
                    "verify_deployed",
                    return_value=ExecutionResult(
                        stage=ExecutionStage.VERIFY,
                        success=False,
                        message="mismatch",
                    ),
                ),
            ):
                result = e.execute(proposal)
                assert "VERIFY_ROLLED_BACK" in result.final_state

    @pytest.mark.slow
    def test_default_quality_gate_runs_mypy_for_src_python_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / "src" / "maref" / "generated.py"
            target.parent.mkdir(parents=True)
            target.write_text("VALUE: int = 1\n")
            executor = SelfExecutor(project_root=tmp)
            code = GeneratedCode(
                file_path=str(target),
                content="VALUE: int = 1\n",
                target_module="generated",
            )
            pipeline = ExecutionPipelineRecord(pipeline_id="p", proposal_id="prop")
            completed = MagicMock()
            completed.returncode = 0
            completed.stdout = ""
            completed.stderr = ""

            with patch("maref.recursive.self_executor.subprocess.run", return_value=completed) as run:
                result = executor._default_quality_gate(code, pipeline)

            commands = [call.args[0] for call in run.call_args_list]
            assert any(command[0] == "mypy" for command in commands)
            assert result.success is True

    @pytest.mark.slow
    def test_execute_rolls_back_when_quality_gate_fails(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / "target.py"
            target.write_text("VALUE = 1\n")
            e = SelfExecutor(project_root=tmp)
            proposal = MockProposal(
                proposal_id="p-quality",
                change_type="refactor_module",
                target_files=[str(target)],
                proposed_arch="target",
                rationale="refactor",
            )
            e._quality_gate = lambda code, pipeline: ExecutionResult(
                stage=ExecutionStage.VERIFY,
                success=False,
                message="pytest failed",
            )

            result = e.execute(proposal)

            assert result.final_state == "FAILED_VERIFY_ROLLED_BACK"
            assert result.rollback_performed is True
            assert target.read_text() == "VALUE = 1\n"

    @pytest.mark.slow
    def test_execute_success(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            e = SelfExecutor(project_root=tmp)
            proposal = MockProposal(proposal_id="p1")

            file_path = os.path.join(tmp, "test_out.py")
            code = GeneratedCode(
                file_path=file_path, content="x = 1", target_module="mod"
            )

            mock_no_threat = MagicMock()
            mock_no_threat.blocked = False

            with (
                patch.object(e._code_gen, "generate", return_value=[code]),
                patch.object(
                    e._safety_gate,
                    "detect_core_removal",
                    return_value=mock_no_threat,
                ),
                patch.object(e._safety_gate, "detect_combinatorial_explosion", return_value=mock_no_threat),
                patch.object(e, "_do_ai_stench_check", return_value=None),
                patch.object(e, "_do_intent_drift_check", return_value=None),
            ):
                result = e.execute(proposal)
                assert result.final_state == "SUCCESS"

    @pytest.mark.slow
    def test_dry_run_no_code(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")
        with patch.object(e._code_gen, "generate", return_value=[]):
            result = e.dry_run(proposal)
            assert result.final_state == "DRY_RUN_NO_CODE"

    @pytest.mark.slow
    def test_dry_run_ok(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        with patch.object(e._code_gen, "generate", return_value=[code]):
            result = e.dry_run(proposal)
            assert result.final_state == "DRY_RUN_OK"

    @pytest.mark.slow
    def test_dry_run_ast_fail(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")
        code = GeneratedCode(
            file_path="/tmp/f.py", content="def (", target_module="mod"
        )
        with patch.object(e._code_gen, "generate", return_value=[code]):
            result = e.dry_run(proposal)
            assert result.final_state == "DRY_RUN_AST_FAIL"

    @pytest.mark.slow
    def test_dry_run_exception(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")
        with patch.object(e._code_gen, "generate", side_effect=RuntimeError("boom")):
            result = e.dry_run(proposal)
            assert result.final_state == "DRY_RUN_ERROR"

    @pytest.mark.slow
    def test_attach_intent_drift_detector(self) -> None:
        e = SelfExecutor()
        detector = MagicMock()
        e.attach_intent_drift_detector(detector)
        assert e._intent_drift_detector is detector

    @pytest.mark.slow
    def test_attach_gene_pipeline(self) -> None:
        e = SelfExecutor()
        pipeline = MagicMock()
        e.attach_gene_pipeline(pipeline)
        assert e._gene_pipeline is pipeline

    @pytest.mark.slow
    def test_health_check(self) -> None:
        e = SelfExecutor()
        health = e.health_check()
        assert health["max_rounds"] == 3
        assert health["history_length"] == 0
        assert health["deployed_file_count"] == 0
        assert health["successful_pipelines"] == 0
        assert health["failed_pipelines"] == 0
        assert health["rollback_count"] == 0

    @pytest.mark.slow
    def test_intent_drift_check_no_detector(self) -> None:
        e = SelfExecutor()
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        assert e._do_intent_drift_check(code) is None

    @pytest.mark.slow
    def test_intent_drift_check_blocked(self) -> None:
        e = SelfExecutor()
        detector = MagicMock()
        result = MagicMock()
        result.blocked = True
        result.intent_valid = False
        detector.evaluate_code.return_value = result
        e.attach_intent_drift_detector(detector)
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        check = e._do_intent_drift_check(code)
        assert check is not None
        assert check.success is False

    @pytest.mark.slow
    def test_ai_stench_check_no_method(self) -> None:
        e = SelfExecutor()
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        with patch.object(e._safety_gate, "detect_ai_stench", side_effect=AttributeError):
            assert e._do_ai_stench_check(code) is None

    @pytest.mark.slow
    def test_ai_stench_check_blocked(self) -> None:
        e = SelfExecutor()
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        mock_threat = MagicMock()
        mock_threat.blocked = True
        mock_threat.threat_type = "stench"
        mock_threat.reason = "ai generated"
        with patch.object(
            e._safety_gate, "detect_ai_stench", return_value=mock_threat
        ):
            check = e._do_ai_stench_check(code)
            assert check is not None
            assert check.success is False

    @pytest.mark.slow
    def test_do_auto_gene_extraction_no_pipeline(self) -> None:
        e = SelfExecutor()
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        e._do_auto_gene_extraction(code, "rollback", "reason")
        assert e._gene_pipeline is None

    @pytest.mark.slow
    def test_do_auto_gene_extraction_rollback(self) -> None:
        e = SelfExecutor()
        pipeline = MagicMock()
        e.attach_gene_pipeline(pipeline)
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        e._do_auto_gene_extraction(code, "rollback", "deploy failed")
        pipeline.extract_from_rollback.assert_called_once()

    @pytest.mark.slow
    def test_do_auto_gene_extraction_block(self) -> None:
        e = SelfExecutor()
        pipeline = MagicMock()
        e.attach_gene_pipeline(pipeline)
        code = GeneratedCode(
            file_path="/tmp/f.py", content="x = 1", target_module="mod"
        )
        e._do_auto_gene_extraction(code, "block", "stench")
        pipeline.extract_from_block.assert_called_once()

    @pytest.mark.slow
    def test_history_property_returns_copy(self) -> None:
        e = SelfExecutor()
        from maref.recursive.self_executor import ExecutionPipelineRecord
        e._history.append(
            ExecutionPipelineRecord(pipeline_id="p1", proposal_id="prop1")
        )
        hist = e.history
        assert len(hist) == 1
        hist.clear()
        assert len(e.history) == 1

    @pytest.mark.slow
    def test_stage_code_generation_exception(self) -> None:
        e = SelfExecutor()
        proposal = MockProposal(proposal_id="p1")
        pipeline = ExecutionPipelineRecord(
            pipeline_id="p1", proposal_id="prop1"
        )
        with patch.object(e._code_gen, "generate", side_effect=RuntimeError("boom")):
            result = e._stage_code_generation(proposal, pipeline)
            assert result.success is False

    @pytest.mark.slow
    def test_stage_ast_validation_none_code(self) -> None:
        e = SelfExecutor()
        pipeline = ExecutionPipelineRecord(
            pipeline_id="p1", proposal_id="prop1"
        )
        result = e._stage_ast_validation(None, pipeline)
        assert result.success is False


class TestCodeGeneratorTypeScript:
    @pytest.mark.slow
    def test_classify_ts_proposal_by_rationale(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="p", rationale="refactor typescript module")
        assert cg._classify_proposal(p) == "refactor_typescript"

    @pytest.mark.slow
    def test_classify_ts_proposal_by_target_files(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(
            proposal_id="p",
            rationale="refactor module",
            target_files=["src/ui/component.tsx"],
        )
        assert cg._classify_proposal(p) == "refactor_typescript"

    @pytest.mark.slow
    def test_classify_ts_test_proposal_by_target_files(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(
            proposal_id="p",
            rationale="add tests for coverage",
            target_files=["src/ui/component.test.ts"],
        )
        assert cg._classify_proposal(p) == "add_typescript_tests"

    @pytest.mark.slow
    def test_generate_refactor_ts(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="ts-001", rationale="refactor typescript module")
        result = cg._generate_refactor_ts(p, Path("/tmp/test.ts"))
        assert result.file_path == "/tmp/test.ts"
        assert result.language == "typescript"
        assert "export interface R31AutoGenerated" in result.content
        assert "export function createFromProposal" in result.content

    @pytest.mark.slow
    def test_generate_tests_ts(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(proposal_id="ts-test-001", rationale="add typescript tests")
        result = cg._generate_tests_ts(p, Path("/tmp/test.spec.ts"))
        assert result.file_path == "/tmp/test.spec.ts"
        assert result.language == "typescript"
        assert "from 'vitest'" in result.content
        assert "describe(" in result.content
        assert "expect(true).toBe(true)" in result.content

    @pytest.mark.slow
    def test_generate_ts_via_dispatch_refactor(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(
            proposal_id="p",
            rationale="refactor typescript module",
        )
        results = cg.generate(p, project_root="/tmp")
        assert len(results) == 1
        assert results[0].language == "typescript"
        assert results[0].file_path.endswith(".py")  # default path is .py
        assert "export interface R31AutoGenerated" in results[0].content

    @pytest.mark.slow
    def test_generate_ts_via_dispatch_tests(self) -> None:
        cg = CodeGenerator()
        p = MockProposal(
            proposal_id="p",
            rationale="add tests for typescript coverage",
            target_files=["/tmp/test.spec.ts"],
        )
        results = cg.generate(p, project_root="/tmp")
        assert len(results) == 1
        assert results[0].language == "typescript"
        assert results[0].file_path.endswith(".ts")
        assert "from 'vitest'" in results[0].content


class TestASTSandboxTypeScript:
    @pytest.mark.slow
    def test_validate_ts_code_skipped(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/test.ts",
            content="export const x: number = 1;\n",
            target_module="test",
            language="typescript",
        )
        result = sandbox.validate(code)
        assert result.is_valid is True
        assert any("skipped" in w.lower() for w in result.warnings)

    @pytest.mark.slow
    def test_validate_tsx_code_skipped(self) -> None:
        sandbox = ASTSandbox()
        code = GeneratedCode(
            file_path="/tmp/test.tsx",
            content="const App = () => <div>hello</div>;\n",
            target_module="test",
            language="typescript",
        )
        result = sandbox.validate(code)
        assert result.is_valid is True
        assert any("skipped" in w.lower() for w in result.warnings)
