from __future__ import annotations

import ast
import os
import shutil
import tempfile
import time
import traceback
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

from maref.recursive.safety_gate_v2 import SafetyGateV2
from maref.recursive.unified_audit import UnifiedAuditRecord, UnifiedAuditStore, make_record_id


class ExecutionStage(Enum):
    CODE_GEN = "code_generation"
    AST_VALIDATE = "ast_validation"
    SAFETY_GATE = "safety_gate"
    DEPLOY = "deployment"
    VERIFY = "verification"
    ROLLBACK = "rollback"
    COMPLETE = "complete"


@dataclass
class GeneratedCode:
    file_path: str
    content: str
    target_module: str
    language: str = "python"


@dataclass
class ASTValidationResult:
    is_valid: bool
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    ast_tree: ast.Module | None = None
    imports: list[str] = field(default_factory=list)
    classes_found: list[str] = field(default_factory=list)
    functions_found: list[str] = field(default_factory=list)


@dataclass
class ExecutionResult:
    stage: ExecutionStage
    success: bool
    message: str
    details: dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    @property
    def is_failure(self) -> bool:
        return not self.success


@dataclass
class ExecutionPipelineRecord:
    pipeline_id: str
    proposal_id: str
    stages: list[ExecutionResult] = field(default_factory=list)
    final_state: str = "unknown"
    rollback_performed: bool = False
    start_time: float = field(default_factory=time.time)
    end_time: float = 0.0

    def finish(self) -> None:
        self.end_time = time.time()

    @property
    def duration_ms(self) -> float:
        end = self.end_time if self.end_time > 0 else time.time()
        return (end - self.start_time) * 1000.0

    def to_audit_records(self, round_num: int = 31) -> list[UnifiedAuditRecord]:
        records: list[UnifiedAuditRecord] = []
        for result in self.stages:
            outcome = "success" if result.success else "failure"
            records.append(UnifiedAuditRecord(
                record_id=make_record_id("exec", hash((self.pipeline_id, result.stage.value)) % 100000),
                timestamp=result.timestamp,
                layer="evolution",
                round=round_num,
                event_type=f"self_executor_{result.stage.value}",
                source_module="SelfExecutor",
                target_module=self.proposal_id,
                decision=result.stage.value,
                justification=result.message,
                outcome=outcome,
                context_refs=[self.pipeline_id],
            ))
        return records


class CodeGenerator:
    CODE_TEMPLATES: dict[str, str] = {
        "refactor_module": """
from __future__ import annotations
{imports}

{classes_and_functions}
""",
        "add_tests": """
from __future__ import annotations

import pytest
{imports}

{test_classes_and_functions}
""",
    }

    def generate(self, proposal, project_root: str) -> list[GeneratedCode]:
        generated: list[GeneratedCode] = []
        proposal_type = self._classify_proposal(proposal)
        target_paths = self._resolve_target_paths(proposal, project_root)

        for target_path in target_paths:
            if proposal_type == "refactor_module":
                gen = self._generate_refactor(proposal, target_path)
            elif proposal_type == "add_tests":
                gen = self._generate_tests(proposal, target_path)
            elif proposal_type == "remove_unused_imports":
                gen = self._generate_remove_imports(proposal, target_path)
            else:
                gen = GeneratedCode(
                    file_path=str(target_path),
                    content=f"# Auto-generated by SelfExecutor for proposal: {proposal.proposal_id}\n"
                            f"# Rationale: {proposal.rationale}\n",
                    target_module=proposal.proposed_arch if hasattr(proposal, 'proposed_arch') else str(target_path),
                )
            if gen:
                generated.append(gen)

        return generated

    def _classify_proposal(self, proposal) -> str:
        if hasattr(proposal, 'change_type') and proposal.change_type is not None:
            ct = str(proposal.change_type.value if hasattr(proposal.change_type, 'value') else proposal.change_type)
            if 'add_test' in ct.lower():
                return "add_tests"
            if 'remove_unused_import' in ct.lower():
                return "remove_unused_imports"
            if 'refactor_module' in ct.lower():
                return "refactor_module"
        rationale = getattr(proposal, 'rationale', '').lower()
        proposed = getattr(proposal, 'proposed_arch', '').lower()
        if 'test' in rationale or 'coverage' in rationale:
            return "add_tests"
        if 'unused import' in rationale or 'cleanup' in proposed:
            return "remove_unused_imports"
        if 'refactor' in rationale or 'restructure' in rationale:
            return "refactor_module"
        return "generic"

    def _resolve_target_paths(self, proposal, project_root: str) -> list[Path]:
        if hasattr(proposal, 'target_files') and proposal.target_files:
            return [Path(p) for p in proposal.target_files]
        target = self._resolve_target_path(proposal, project_root)
        return [target]

    def _resolve_target_path(self, proposal, project_root: str) -> Path:
        current = getattr(proposal, 'current_arch', '')
        if current and not current.startswith(str(project_root)):
            base = Path(project_root) / "src" / "maref" / "recursive"
            return base / f"r31_executor_generated_{hash(proposal.proposal_id) % 10000}.py"
        return Path(project_root) / "src" / "maref" / "recursive" / \
               f"r31_executor_generated_{hash(proposal.proposal_id) % 10000}.py"

    def _generate_refactor(self, proposal, target_path: Path) -> GeneratedCode:
        content = (
            "from __future__ import annotations\n"
            "\n"
            "import time\n"
            "from dataclasses import dataclass\n"
            "from typing import Any\n"
            "\n"
            "\n"
            "@dataclass\n"
            "class R31AutoGenerated:\n"
            "    proposal_id: str\n"
            "    rationale: str\n"
            "    generated_at: float\n"
            "\n"
            "    @classmethod\n"
            '    def from_proposal(cls, proposal_id: str, rationale: str = "") -> R31AutoGenerated:\n'
            "        return cls(\n"
            "            proposal_id=proposal_id,\n"
            "            rationale=rationale,\n"
            "            generated_at=time.time(),\n"
            "        )\n"
            "\n"
            "    def to_dict(self) -> dict[str, Any]:\n"
            "        return {\n"
            '            "proposal_id": self.proposal_id,\n'
            '            "rationale": self.rationale,\n'
            '            "generated_at": self.generated_at,\n'
            "        }\n"
        )
        return GeneratedCode(
            file_path=str(target_path),
            content=content,
            target_module=getattr(proposal, 'proposed_arch', str(target_path)),
        )

    def _generate_tests(self, proposal, target_path: Path) -> GeneratedCode:
        module_name = target_path.stem
        content = f"""from __future__ import annotations

import pytest


class Test{module_name.title().replace('_', '')}:
    def test_auto_generated_smoke(self) -> None:
        assert True, "Auto-generated test placeholder"

    def test_auto_generated_structure(self) -> None:
        from maref.recursive.self_executor import ExecutionStage
        stages = list(ExecutionStage)
        assert len(stages) >= 5, f"Expected >=5 stages, got {{len(stages)}}"

    def test_auto_generated_round31_bootstrap(self) -> None:
        from maref.recursive.self_executor import SelfExecutor
        executor = SelfExecutor(max_rounds=3)
        assert executor.max_rounds == 3
        assert len(executor.history) == 0
"""
        return GeneratedCode(
            file_path=str(target_path),
            content=content,
            target_module=getattr(proposal, 'proposed_arch', str(target_path)),
        )

    def _generate_remove_imports(self, proposal, target_path: Path) -> GeneratedCode | None:
        import ast as _ast
        try:
            source = target_path.read_text()
            tree = _ast.parse(source)
        except (OSError, SyntaxError):
            return None

        symbols_to_remove = set(
            getattr(proposal, 'affected_symbols', []) or []
        )

        class _ImportRemover(_ast.NodeTransformer):
            def visit_Import(self, node):
                new_names = [
                    alias for alias in node.names
                    if alias.name not in symbols_to_remove
                    and alias.asname not in symbols_to_remove
                ]
                if not new_names:
                    return None
                node.names = new_names
                return node

            def visit_ImportFrom(self, node):
                new_names = [
                    alias for alias in node.names
                    if alias.name not in symbols_to_remove
                    and alias.asname not in symbols_to_remove
                ]
                if not new_names:
                    return None
                node.names = new_names
                return node

        remover = _ImportRemover()
        new_tree = remover.visit(tree)
        if new_tree is None:
            return None
        _ast.fix_missing_locations(new_tree)
        try:
            new_content = _ast.unparse(new_tree)
        except Exception:
            return None

        return GeneratedCode(
            file_path=str(target_path),
            content=new_content,
            target_module=getattr(proposal, 'proposed_arch', str(target_path)),
        )


class ASTSandbox:
    ALLOWED_MODULES = {
        "__future__", "abc", "ast", "collections", "copy", "dataclasses",
        "enum", "functools", "hashlib", "inspect", "itertools", "json",
        "math", "os", "pathlib", "re", "statistics", "string", "subprocess",
        "sys", "textwrap", "time", "traceback", "typing", "uuid", "warnings",
        "pytest", "maref",
    }
    BLOCKED_IMPORTS = {"os.system", "subprocess.call", "subprocess.run",
                        "eval", "exec", "compile", "__import__"}

    def validate(self, code: GeneratedCode) -> ASTValidationResult:
        result = ASTValidationResult(is_valid=True)
        try:
            tree = ast.parse(code.content)
            result.ast_tree = tree
        except SyntaxError as e:
            result.is_valid = False
            result.errors.append(f"SyntaxError: {e}")
            return result

        self._check_imports(tree, result)
        self._check_dangerous_calls(tree, result)
        self._extract_definitions(tree, result)

        return result

    def _check_imports(self, tree: ast.Module, result: ASTValidationResult) -> None:
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    top_module = alias.name.split(".")[0]
                    if top_module not in self.ALLOWED_MODULES:
                        result.warnings.append(f"Unknown import: {alias.name}")
                    result.imports.append(alias.name)
            elif isinstance(node, ast.ImportFrom) and node.module:
                top_module = node.module.split(".")[0]
                if top_module not in self.ALLOWED_MODULES:
                    result.warnings.append(f"Unknown import: {node.module}")
                result.imports.append(node.module)

    def _check_dangerous_calls(self, tree: ast.Module, result: ASTValidationResult) -> None:
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name) and node.func.id in self.BLOCKED_IMPORTS:
                    result.is_valid = False
                    result.errors.append(f"Dangerous call detected: {node.func.id}")
                elif isinstance(node.func, ast.Attribute):
                    full_attr = self._resolve_attribute(node.func)
                    for blocked in self.BLOCKED_IMPORTS:
                        if full_attr.endswith(blocked.split(".")[-1]):
                            result.is_valid = False
                            result.errors.append(f"Dangerous attribute call detected: {full_attr}")
                if isinstance(node.func, ast.Name) and node.func.id == "getattr":
                    if len(node.args) >= 2 and isinstance(node.args[1], ast.Constant):
                        target_func = str(node.args[1].value)
                        for blocked in self.BLOCKED_IMPORTS:
                            if target_func in blocked or blocked.endswith(f".{target_func}"):
                                result.is_valid = False
                                result.errors.append(f"Dangerous getattr bypass detected: getattr(..., '{target_func}')")

    @staticmethod
    def _resolve_attribute(node: ast.Attribute) -> str:
        parts: list[str] = []
        current: Any = node
        while isinstance(current, ast.Attribute):
            parts.append(current.attr)
            current = current.value
        if isinstance(current, ast.Name):
            parts.append(current.id)
        return ".".join(reversed(parts))

    def _extract_definitions(self, tree: ast.Module, result: ASTValidationResult) -> None:
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                result.classes_found.append(node.name)
            elif isinstance(node, ast.FunctionDef):
                result.functions_found.append(node.name)


class AtomicDeployer:
    def __init__(self, backup_dir: str | None = None) -> None:
        self._backup_dir = backup_dir or os.path.join(tempfile.gettempdir(), "maref_executor_backups")
        os.makedirs(self._backup_dir, exist_ok=True)
        self._deployed: dict[str, str] = {}

    def deploy(self, code: GeneratedCode) -> ExecutionResult:
        file_path = code.file_path
        backup_path = os.path.join(
            self._backup_dir,
            f"backup_{int(time.time())}_{os.path.basename(file_path)}",
        )

        try:
            if os.path.exists(file_path):
                shutil.copy2(file_path, backup_path)

            os.makedirs(os.path.dirname(file_path), exist_ok=True)

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code.content)

            if not os.path.exists(file_path):
                raise RuntimeError(f"File not created: {file_path}")

            self._deployed[file_path] = backup_path

            return ExecutionResult(
                stage=ExecutionStage.DEPLOY,
                success=True,
                message=f"Deployed to {file_path}, backup at {backup_path}",
                details={"file_path": file_path, "backup_path": backup_path, "size_bytes": len(code.content)},
            )
        except Exception as e:
            return ExecutionResult(
                stage=ExecutionStage.DEPLOY,
                success=False,
                message=f"Deployment failed: {e}",
                details={"error": str(e), "traceback": traceback.format_exc()},
            )

    def rollback(self, file_path: str) -> ExecutionResult:
        backup_path = self._deployed.get(file_path)
        if not backup_path or not os.path.exists(backup_path):
            return ExecutionResult(
                stage=ExecutionStage.ROLLBACK,
                success=False,
                message=f"No backup found for {file_path}",
                details={"file_path": file_path},
            )

        try:
            shutil.copy2(backup_path, file_path)
            return ExecutionResult(
                stage=ExecutionStage.ROLLBACK,
                success=True,
                message=f"Rolled back {file_path} from {backup_path}",
                details={"file_path": file_path, "backup_path": backup_path},
            )
        except Exception as e:
            return ExecutionResult(
                stage=ExecutionStage.ROLLBACK,
                success=False,
                message=f"Rollback failed: {e}",
                details={"error": str(e)},
            )

    def verify_deployed(self, file_path: str, expected_content: str) -> ExecutionResult:
        try:
            if not os.path.exists(file_path):
                return ExecutionResult(
                    stage=ExecutionStage.VERIFY,
                    success=False,
                    message=f"File not found: {file_path}",
                )
            with open(file_path, encoding="utf-8") as f:
                actual = f.read()
            if actual != expected_content:
                return ExecutionResult(
                    stage=ExecutionStage.VERIFY,
                    success=False,
                    message="Content mismatch after deployment",
                    details={"expected_size": len(expected_content), "actual_size": len(actual)},
                )
            return ExecutionResult(
                stage=ExecutionStage.VERIFY,
                success=True,
                message="Deployment verified",
                details={"file_path": file_path},
            )
        except Exception as e:
            return ExecutionResult(
                stage=ExecutionStage.VERIFY,
                success=False,
                message=f"Verification failed: {e}",
            )

    @property
    def deployed_files(self) -> list[str]:
        return list(self._deployed.keys())


class SelfExecutor:
    def __init__(
        self,
        max_rounds: int = 3,
        project_root: str | None = None,
        audit_store: UnifiedAuditStore | None = None,
    ) -> None:
        self._max_rounds = max_rounds
        self._project_root = project_root or os.getcwd()
        self._audit_store = audit_store or UnifiedAuditStore()
        self._code_gen = CodeGenerator()
        self._sandbox = ASTSandbox()
        self._safety_gate = SafetyGateV2()
        self._deployer = AtomicDeployer()
        self._history: list[ExecutionPipelineRecord] = []

    @property
    def max_rounds(self) -> int:
        return self._max_rounds

    @property
    def history(self) -> list[ExecutionPipelineRecord]:
        return list(self._history)

    @property
    def deployed_files(self) -> list[str]:
        return self._deployer.deployed_files

    def execute(self, proposal, round_num: int = 31) -> ExecutionPipelineRecord:
        pipeline = ExecutionPipelineRecord(
            pipeline_id=f"exec_pipeline_{int(time.time())}_{hash(proposal.proposal_id) % 10000}",
            proposal_id=proposal.proposal_id,
        )

        code_gen_result = self._stage_code_generation(proposal, pipeline)
        pipeline.stages.append(code_gen_result)
        if code_gen_result.is_failure:
            pipeline.final_state = "FAILED_CODE_GEN"
            pipeline.finish()
            self._history.append(pipeline)
            return pipeline

        code = code_gen_result.details.get("generated_code")
        ast_result = self._stage_ast_validation(code, pipeline)
        pipeline.stages.append(ast_result)
        if ast_result.is_failure:
            pipeline.final_state = "FAILED_AST_VALIDATE"
            pipeline.finish()
            self._history.append(pipeline)
            return pipeline

        if not isinstance(code, GeneratedCode):
            pipeline.final_state = "FAILED_NO_CODE"
            pipeline.finish()
            self._history.append(pipeline)
            return pipeline

        safety_result = self._stage_safety_gate(code, proposal, pipeline)
        pipeline.stages.append(safety_result)
        if safety_result.is_failure:
            pipeline.final_state = "FAILED_SAFETY_GATE"
            pipeline.finish()
            self._history.append(pipeline)
            return pipeline

        deploy_result = self._stage_deploy(code, pipeline)
        pipeline.stages.append(deploy_result)
        if deploy_result.is_failure:
            pipeline.stages.append(self._stage_rollback(code.file_path, pipeline))
            pipeline.rollback_performed = True
            pipeline.final_state = "FAILED_DEPLOY_ROLLED_BACK"
            pipeline.finish()
            self._history.append(pipeline)
            return pipeline

        verify_result = self._stage_verify(code, pipeline)
        pipeline.stages.append(verify_result)
        if verify_result.is_failure:
            pipeline.stages.append(self._stage_rollback(code.file_path, pipeline))
            pipeline.rollback_performed = True
            pipeline.final_state = "FAILED_VERIFY_ROLLED_BACK"
            pipeline.finish()
            self._history.append(pipeline)
            return pipeline

        pipeline.final_state = "SUCCESS"
        pipeline.finish()
        self._history.append(pipeline)
        self._audit_pipeline(pipeline, round_num)
        return pipeline

    def _stage_code_generation(self, proposal, pipeline: ExecutionPipelineRecord) -> ExecutionResult:
        try:
            generated = self._code_gen.generate(proposal, self._project_root)
            if not generated:
                return ExecutionResult(
                    stage=ExecutionStage.CODE_GEN,
                    success=False,
                    message="No code generated",
                    details={"proposal_id": proposal.proposal_id},
                )
            code = generated[0]
            return ExecutionResult(
                stage=ExecutionStage.CODE_GEN,
                success=True,
                message=f"Generated code for {code.file_path} ({len(code.content)} bytes)",
                details={
                    "generated_code": code,
                    "file_path": code.file_path,
                    "size_bytes": len(code.content),
                },
            )
        except Exception as e:
            return ExecutionResult(
                stage=ExecutionStage.CODE_GEN,
                success=False,
                message=f"Code generation failed: {e}",
                details={"error": str(e), "traceback": traceback.format_exc()},
            )

    def _stage_ast_validation(self, code: GeneratedCode | None,
                               pipeline: ExecutionPipelineRecord) -> ExecutionResult:
        if code is None:
            return ExecutionResult(
                stage=ExecutionStage.AST_VALIDATE,
                success=False,
                message="No code to validate",
            )
        validation = self._sandbox.validate(code)
        return ExecutionResult(
            stage=ExecutionStage.AST_VALIDATE,
            success=validation.is_valid,
            message=f"AST validation: {'PASS' if validation.is_valid else 'FAIL'} "
                    f"({len(validation.errors)} errors, {len(validation.warnings)} warnings)",
            details={
                "is_valid": validation.is_valid,
                "errors": validation.errors,
                "warnings": validation.warnings,
                "imports": validation.imports,
                "classes": validation.classes_found,
                "functions": validation.functions_found,
            },
        )

    def _stage_safety_gate(self, code: GeneratedCode, proposal,
                            pipeline: ExecutionPipelineRecord) -> ExecutionResult:
        threat = self._safety_gate.detect_core_removal(code.target_module)
        if threat.blocked:
            return ExecutionResult(
                stage=ExecutionStage.SAFETY_GATE,
                success=False,
                message=f"SafetyGate blocked: {threat.threat_type} - {threat.reason}",
                details={"threat": threat},
            )

        batch_check = self._safety_gate.detect_combinatorial_explosion([{
            "target": code.file_path,
            "action": "deploy",
            "size": len(code.content),
        }])
        if batch_check.blocked:
            return ExecutionResult(
                stage=ExecutionStage.SAFETY_GATE,
                success=False,
                message=f"SafetyGate blocked: {batch_check.threat_type} - {batch_check.reason}",
                details={"threat": batch_check},
            )

        return ExecutionResult(
            stage=ExecutionStage.SAFETY_GATE,
            success=True,
            message="SafetyGate passed all checks",
            details={"threats_checked": ["core_removal", "combinatorial_explosion"]},
        )

    def _stage_deploy(self, code: GeneratedCode, pipeline: ExecutionPipelineRecord) -> ExecutionResult:
        return self._deployer.deploy(code)

    def _stage_verify(self, code: GeneratedCode, pipeline: ExecutionPipelineRecord) -> ExecutionResult:
        return self._deployer.verify_deployed(code.file_path, code.content)

    def _stage_rollback(self, file_path: str, pipeline: ExecutionPipelineRecord) -> ExecutionResult:
        return self._deployer.rollback(file_path)

    def _audit_pipeline(self, pipeline: ExecutionPipelineRecord, round_num: int) -> None:
        records = pipeline.to_audit_records(round_num)
        for record in records:
            self._audit_store.append(record)

    def dry_run(self, proposal) -> ExecutionPipelineRecord:
        pipeline = ExecutionPipelineRecord(
            pipeline_id=f"dry_run_{int(time.time())}_{hash(proposal.proposal_id) % 10000}",
            proposal_id=proposal.proposal_id,
        )

        try:
            generated = self._code_gen.generate(proposal, self._project_root)
            if not generated:
                pipeline.final_state = "DRY_RUN_NO_CODE"
                pipeline.finish()
                return pipeline

            code = generated[0]
            validation = self._sandbox.validate(code)

            pipeline.stages.append(ExecutionResult(
                stage=ExecutionStage.CODE_GEN,
                success=True,
                message=f"Dry-run: generated {len(code.content)} bytes",
                details={"file_path": code.file_path},
            ))
            pipeline.stages.append(ExecutionResult(
                stage=ExecutionStage.AST_VALIDATE,
                success=validation.is_valid,
                message=f"Dry-run: AST {'valid' if validation.is_valid else 'invalid'}",
                details={"errors": validation.errors},
            ))

            pipeline.final_state = "DRY_RUN_OK" if validation.is_valid else "DRY_RUN_AST_FAIL"
        except Exception as e:
            pipeline.stages.append(ExecutionResult(
                stage=ExecutionStage.CODE_GEN,
                success=False,
                message=f"Dry-run failed: {e}",
            ))
            pipeline.final_state = "DRY_RUN_ERROR"

        pipeline.finish()
        return pipeline

    def health_check(self) -> dict[str, Any]:
        return {
            "max_rounds": self._max_rounds,
            "history_length": len(self._history),
            "deployed_file_count": len(self._deployer.deployed_files),
            "audit_records": self._audit_store.count(),
            "successful_pipelines": sum(
                1 for p in self._history if p.final_state == "SUCCESS"
            ),
            "failed_pipelines": sum(
                1 for p in self._history if p.final_state.startswith("FAILED")
            ),
            "rollback_count": sum(1 for p in self._history if p.rollback_performed),
        }
