#!/usr/bin/env python3
"""
策略规则进化提案器

综合多源燃料 (rule_effectiveness + agent_health + redline_candidates + vaccine_pipeline)
生成 PR 级策略变更提案

提案类型:
- threshold_adjustment: 探针/规则阈值调整
- new_rule: 新增治理规则
- redline_candidate: 红线模式入库
- rule_deprecation: 废弃失效规则
- rule_replacement: 规则替换重写

输出: evolution_fuel 中 policy_proposal 类型燃料，可直接转为 GitHub PR
"""

import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    import duckdb
    DUCKDB_AVAILABLE = True
except ImportError:
    DUCKDB_AVAILABLE = False

from maref_config import config_path

LAKE_ROOT = Path(os.environ.get("MAREF_GOVERNANCE_LAKE", "/Volumes/1TB-M2/maref-governance-lake"))


def _load_fuel(fuel_type: str, days: int = 30) -> list[dict]:
    """加载 evolution_fuel"""
    if not DUCKDB_AVAILABLE:
        return []

    try:
        conn = duckdb.connect()
        date_cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y%m%d")
        df = conn.execute(f"""
            SELECT * FROM read_parquet('{LAKE_ROOT}/analytics/evolution_fuel/**/*.parquet')
            WHERE date >= '{date_cutoff}' AND fuel_type = '{fuel_type}'
        """).fetchdf()
        result = []
        for _, row in df.iterrows():
            result.append(row.to_dict())
        conn.close()
        return result
    except Exception:
        return []


def _load_rule_effectiveness(days: int = 30) -> list[dict]:
    """加载规则有效度"""
    if not DUCKDB_AVAILABLE:
        return []

    try:
        conn = duckdb.connect()
        date_cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")
        df = conn.execute(f"""
            SELECT * FROM read_parquet('{LAKE_ROOT}/analytics/rule_effectiveness/**/*.parquet')
            WHERE date >= '{date_cutoff}'
        """).fetchdf()
        result = []
        for _, row in df.iterrows():
            result.append(row.to_dict())
        conn.close()
        return result
    except Exception:
        return []


def _load_agent_health(days: int = 30) -> list[dict]:
    """加载 Agent 健康"""
    if not DUCKDB_AVAILABLE:
        return []

    try:
        conn = duckdb.connect()
        date_cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")
        df = conn.execute(f"""
            SELECT * FROM read_parquet('{LAKE_ROOT}/analytics/agent_health_index/**/*.parquet')
            WHERE date >= '{date_cutoff}'
        """).fetchdf()
        result = []
        for _, row in df.iterrows():
            result.append(row.to_dict())
        conn.close()
        return result
    except Exception:
        return []


def _load_vaccines() -> list[dict]:
    """加载疫苗"""
    try:
        from maref_config import vaccine_path
        vp = vaccine_path("vaccines.json")
        if vp.exists():
            with open(vp) as f:
                return json.load(f)
    except Exception:
        pass
    return []


def _generate_proposal_id(fuel_type: str, source: str) -> str:
    """生成提案 ID"""
    import hashlib
    base = f"{fuel_type}:{source}:{datetime.now(timezone.utc).strftime('%Y%m%d%H%M')}"
    return f"PROP-{hashlib.sha256(base.encode()).hexdigest()[:8].upper()}"


def _render_pr_body(proposal: dict) -> str:
    """渲染 PR Body Markdown"""
    md = [
        f"# {proposal['title']}",
        "",
        f"**Proposal ID**: {proposal['proposal_id']}",
        f"**Type**: {proposal['fuel_type']}",
        f"**Priority**: {proposal['priority']}",
        f"**Source**: {proposal['source']}",
        f"**Created**: {proposal['created_at']}",
        "",
        "## 摘要",
        proposal['description'],
        "",
        "## 证据链",
        "```json",
        json.dumps(proposal['evidence'], indent=2, ensure_ascii=False),
        "```",
        "",
        "## 具体变更",
        "```json",
        json.dumps(proposal['proposed_change'], indent=2, ensure_ascii=False),
        "```",
        "",
        "## 影响评估",
        "```json",
        json.dumps(proposal['impact_estimate'], indent=2, ensure_ascii=False),
        "```",
        "",
        "## 部署计划",
        "1. 代码审查通过",
        "2. Staging 环境验证 (运行 probe_sampler + 规则有效度)",
        "3. 灰度发布 (10% 流量)",
        "4. 全量发布",
        "5. 监控 24h 确认无回归",
        "",
        "## 回滚方案",
        "如出现回归，立即 revert PR 并重启 sidecar",
        "",
        "---",
        "*Auto-generated by policy_evolution_proposer*",
    ]
    return "\n".join(md)


def propose_from_rule_effectiveness(rule_data: list[dict]) -> list[dict]:
    """基于规则有效度生成提案"""
    proposals = []

    # 聚合最新版本
    latest_by_rule = {}
    for r in rule_data:
        rid = r.get("rule_id", "")
        if rid not in latest_by_rule or r.get("timestamp", 0) > latest_by_rule[rid].get("timestamp", 0):
            latest_by_rule[rid] = r

    for r in latest_by_rule.values():
        fp = r.get("false_positive_est", 0)
        drift = r.get("drift_score", 0)
        tier = r.get("effectiveness_tier", "medium")
        rec = r.get("recommendation", "keep")
        rule_id = r.get("rule_id", "")
        total = r.get("total_evaluations", 0)

        if total < 50:
            continue  # 样本不足

        if rec == "deprecate" and fp > 0.3:
            proposals.append({
                "fuel_type": "policy_proposal",
                "source": "rule_effectiveness",
                "priority": 1,
                "proposal_id": _generate_proposal_id("rule_deprecation", rule_id),
                "title": f"废弃高误报规则: {rule_id}",
                "description": f"规则 {rule_id} 误报率 {fp:.1%} (样本 {total})，有效度分级 {tier}，建议废弃",
                "evidence": r,
                "proposed_change": {
                    "type": "rule_deprecation",
                    "rule_id": rule_id,
                    "action": "deprecate",
                    "reason": f"FP={fp:.1%}, drift={drift:.2f}",
                },
                "impact_estimate": {
                    "coverage_loss": "low",
                    "false_positive_reduction": f"{fp:.1%}",
                    "affected_tools": "unknown",
                },
                "status": "proposed",
                "created_at": datetime.now(timezone.utc).isoformat(),
            })

        elif rec == "tune" and drift > 0.3:
            proposals.append({
                "fuel_type": "policy_proposal",
                "source": "rule_effectiveness",
                "priority": 2,
                "proposal_id": _generate_proposal_id("threshold_adjustment", rule_id),
                "title": f"调整规则阈值: {rule_id}",
                "description": f"规则 {rule_id} 漂移分数 {drift:.2f}，建议重新校准阈值",
                "evidence": r,
                "proposed_change": {
                    "type": "threshold_adjustment",
                    "rule_id": rule_id,
                    "action": "recalibrate",
                    "suggested_threshold": "基于最新分布重新计算",
                },
                "impact_estimate": {
                    "drift_reduction": f"{drift:.0%}",
                    "affected_tools": "unknown",
                },
                "status": "proposed",
                "created_at": datetime.now(timezone.utc).isoformat(),
            })

        elif fp < 0.05 and drift < 0.1 and tier == "high":
            # 高质量规则，考虑推广
            proposals.append({
                "fuel_type": "policy_proposal",
                "source": "rule_effectiveness",
                "priority": 3,
                "proposal_id": _generate_proposal_id("rule_promotion", rule_id),
                "title": f"推广高质量规则模式: {rule_id}",
                "description": f"规则 {rule_id} FP={fp:.1%}, drift={drift:.2f}，表现优秀，建议将模式推广到同类工具",
                "evidence": r,
                "proposed_change": {
                    "type": "new_rule",
                    "template_rule": rule_id,
                    "action": "extend_to_similar_tools",
                },
                "impact_estimate": {
                    "coverage_gain": "medium",
                    "false_positive_risk": "low",
                },
                "status": "proposed",
                "created_at": datetime.now(timezone.utc).isoformat(),
            })

    return proposals


def propose_from_agent_health(health_data: list[dict]) -> list[dict]:
    """基于 Agent 健康生成提案"""
    proposals = []

    latest_by_agent = {}
    for h in health_data:
        aid = h.get("agent_id", "")
        if aid not in latest_by_agent or h.get("timestamp", 0) > latest_by_agent[aid].get("timestamp", 0):
            latest_by_agent[aid] = h

    for h in latest_by_agent.values():
        tier = h.get("health_tier", "excellent")
        agent = h.get("agent_id", "")
        viol = h.get("violation_rate", 0)
        intercept = h.get("interception_rate", 0)
        trust = h.get("trust_score", 50)

        if tier in ("poor", "critical"):
            proposals.append({
                "fuel_type": "policy_proposal",
                "source": "agent_health",
                "priority": 1,
                "proposal_id": _generate_proposal_id("agent_quarantine", agent),
                "title": f"隔离不健康 Agent: {agent}",
                "description": f"Agent {agent} 健康度 {tier} (trust={trust:.0f}, viol={viol:.1%})，建议触发隔离/降级",
                "evidence": h,
                "proposed_change": {
                    "type": "agent_sanction",
                    "agent_id": agent,
                    "action": "quarantine",
                    "reason": f"health_tier={tier}, violation_rate={viol:.2%}",
                },
                "impact_estimate": {
                    "availability_impact": "medium",
                    "security_gain": "high",
                },
                "status": "proposed",
                "created_at": datetime.now(timezone.utc).isoformat(),
            })

        elif viol < 0.01 and intercept < 0.01 and trust > 90:
            proposals.append({
                "fuel_type": "policy_proposal",
                "source": "agent_health",
                "priority": 3,
                "proposal_id": _generate_proposal_id("agent_promotion", agent),
                "title": f"提升 Agent 信任等级: {agent}",
                "description": f"Agent {agent} 长期零违规 (trust={trust:.0f})，建议提升信任等级减少拦截",
                "evidence": h,
                "proposed_change": {
                    "type": "trust_adjustment",
                    "agent_id": agent,
                    "action": "increase_trust",
                    "new_trust_level": "TRUSTED",
                },
                "impact_estimate": {
                    "latency_reduction": "medium",
                    "throughput_gain": "high",
                },
                "status": "proposed",
                "created_at": datetime.now(timezone.utc).isoformat(),
            })

    return proposals


def propose_from_redline_candidates(redline_data: list[dict]) -> list[dict]:
    """基于红线候选生成提案"""
    proposals = []

    for r in redline_data:
        if r.get("status") != "proposed":
            continue

        proposals.append({
            "fuel_type": "policy_proposal",
            "source": "redline_candidate",
            "priority": r.get("priority", 2),
            "proposal_id": _generate_proposal_id("redline_candidate", r.get("source", "unknown")),
            "title": f"红线入库: {r.get('title', '')[:80]}",
            "description": r.get("description", ""),
            "evidence": r.get("evidence", {}),
            "proposed_change": r.get("proposed_change", {}),
            "impact_estimate": r.get("impact_estimate", {}),
            "status": "proposed",
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

    return proposals


def propose_from_vaccines(vaccines: list[dict]) -> list[dict]:
    """基于疫苗生成提案"""
    proposals = []

    for v in vaccines:
        if v.get("status") != "candidate":
            continue

        proposals.append({
            "fuel_type": "policy_proposal",
            "source": "vaccine_pipeline",
            "priority": 2,
            "proposal_id": _generate_proposal_id("vaccine_deployment", v.get("vaccine_id", "")),
            "title": f"部署疫苗: {v.get('vaccine_id', '')}",
            "description": f"疫苗 {v.get('vaccine_id')} 针对 {v.get('attack_class')} (来自模式 {v.get('source_pattern', '')})",
            "evidence": {
                "vaccine": v,
                "pattern_source": v.get("source_pattern"),
            },
            "proposed_change": {
                "type": "vaccine_deployment",
                "vaccine_id": v.get("vaccine_id"),
                "action": "deploy_to_safety_gate",
                "rule_config": v.get("product", {}),
            },
            "impact_estimate": {
                "attack_prevention": "high",
                "false_positive_risk": "medium",
            },
            "status": "proposed",
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

    return proposals


def main():
    parser = argparse.ArgumentParser(description="策略规则进化提案器")
    parser.add_argument("--days", type=int, default=30, help="回溯天数")
    parser.add_argument("--dry-run", action="store_true", help="只打印不写入")
    parser.add_argument("--export-pr", action="store_true", help="导出 PR 文件")
    args = parser.parse_args()

    print("=" * 60)
    print("策略规则进化提案器")
    print("=" * 60)

    if not DUCKDB_AVAILABLE:
        print("❌ 需要 duckdb")
        return 1

    print(f"\n📊 加载燃料数据 (回溯 {args.days} 天)...")
    rule_data = _load_rule_effectiveness(args.days)
    health_data = _load_agent_health(args.days)
    redline_data = _load_fuel("redline_candidate", args.days)
    vaccines = _load_vaccines()

    print(f"   规则有效度: {len(rule_data)}")
    print(f"   Agent 健康: {len(health_data)}")
    print(f"   红线候选: {len(redline_data)}")
    print(f"   疫苗: {len(vaccines)}")

    all_proposals = []

    # 1. 规则有效度 -> 提案
    print("\n📝 生成规则演进提案...")
    props = propose_from_rule_effectiveness(rule_data)
    print(f"   生成: {len(props)}")
    all_proposals.extend(props)

    # 2. Agent 健康 -> 提案
    print("\n📝 生成 Agent 治理提案...")
    props = propose_from_agent_health(health_data)
    print(f"   生成: {len(props)}")
    all_proposals.extend(props)

    # 3. 红线候选 -> 提案
    print("\n📝 生成红线入库提案...")
    props = propose_from_redline_candidates(redline_data)
    print(f"   生成: {len(props)}")
    all_proposals.extend(props)

    # 4. 疫苗 -> 提案
    print("\n📝 生成疫苗部署提案...")
    props = propose_from_vaccines(vaccines)
    print(f"   生成: {len(props)}")
    all_proposals.extend(props)

    # 去重
    seen = set()
    unique = []
    for p in all_proposals:
        key = p.get("title", "")[:100]
        if key not in seen:
            seen.add(key)
            unique.append(p)

    # 按优先级排序
    unique.sort(key=lambda x: (x.get("priority", 99), -len(x.get("evidence", {}))))

    print(f"\n{'=' * 60}")
    print(f"总提案数: {len(unique)} (去重前: {len(all_proposals)})")
    for p in unique:
        print(f"  [P{p.get('priority',99)}] {p['title'][:60]}")
    print(f"{'=' * 60}")

    if args.dry_run:
        print("\n[dry-run] 提案预览:")
        for p in unique[:5]:
            print(f"\n--- {p['proposal_id']} ---")
            print(f"  {p['title']}")
            print(f"  Type: {p.get('proposed_change',{}).get('type','')}")
        return 0

    # 写入 evolution_fuel
    fuel_file = LAKE_ROOT / "analytics" / "evolution_fuel" / f"policy_proposals_{datetime.now(timezone.utc).strftime('%Y%m%d')}.json"
    fuel_file.parent.mkdir(parents=True, exist_ok=True)

    existing = []
    if fuel_file.exists():
        try:
            with open(fuel_file) as f:
                existing = json.load(f)
        except Exception:
            pass

    all_fuel = existing + unique
    with open(fuel_file, "w") as f:
        json.dump(all_fuel, f, indent=2, ensure_ascii=False)

    print(f"✅ 提案已写入: {fuel_file}")
    print(f"   总燃料数: {len(all_fuel)} (新增: {len(unique)})")

    # 导出 PR 文件
    if args.export_pr:
        pr_dir = Path("docs/proposals") / datetime.now(timezone.utc).strftime("%Y%m%d")
        pr_dir.mkdir(parents=True, exist_ok=True)
        for p in unique:
            pr_file = pr_dir / f"{p['proposal_id']}.md"
            with open(pr_file, "w") as f:
                f.write(_render_pr_body(p))
        print(f"📄 PR 文件已导出到: {pr_dir}")

    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())