apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maref-secrets
  namespace: maref
spec:
  encryptedData:
    hmac-signing-key: <REPLACE_WITH_ENCRYPTED_VALUE>
  template:
    metadata:
      name: maref-secrets
      namespace: maref
    type: Opaque
